#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFoodChoice
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SmartFoodChoice")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Login(tbl_Login instance);
    partial void Updatetbl_Login(tbl_Login instance);
    partial void Deletetbl_Login(tbl_Login instance);
    partial void Inserttbl_Overzicht(tbl_Overzicht instance);
    partial void Updatetbl_Overzicht(tbl_Overzicht instance);
    partial void Deletetbl_Overzicht(tbl_Overzicht instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SmartFoodChoice.Properties.Settings.Default.ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Login> tbl_Logins
		{
			get
			{
				return this.GetTable<tbl_Login>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Overzicht> tbl_Overzichts
		{
			get
			{
				return this.GetTable<tbl_Overzicht>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Login")]
	public partial class tbl_Login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Recht;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRechtChanging(string value);
    partial void OnRechtChanged();
    #endregion
		
		public tbl_Login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(32)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(32)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recht", DbType="VarChar(32)")]
		public string Recht
		{
			get
			{
				return this._Recht;
			}
			set
			{
				if ((this._Recht != value))
				{
					this.OnRechtChanging(value);
					this.SendPropertyChanging();
					this._Recht = value;
					this.SendPropertyChanged("Recht");
					this.OnRechtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Overzicht")]
	public partial class tbl_Overzicht : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Product_ID;
		
		private string _Smiley;
		
		private System.Nullable<System.DateTime> _Datum_en_Tijd;
		
		private string _Productnaam;
		
		private string _CO_2_uitstoot;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduct_IDChanging(int value);
    partial void OnProduct_IDChanged();
    partial void OnSmileyChanging(string value);
    partial void OnSmileyChanged();
    partial void OnDatum_en_TijdChanging(System.Nullable<System.DateTime> value);
    partial void OnDatum_en_TijdChanged();
    partial void OnProductnaamChanging(string value);
    partial void OnProductnaamChanged();
    partial void OnCO_2_uitstootChanging(string value);
    partial void OnCO_2_uitstootChanged();
    #endregion
		
		public tbl_Overzicht()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Smiley", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Smiley
		{
			get
			{
				return this._Smiley;
			}
			set
			{
				if ((this._Smiley != value))
				{
					this.OnSmileyChanging(value);
					this.SendPropertyChanging();
					this._Smiley = value;
					this.SendPropertyChanged("Smiley");
					this.OnSmileyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Datum en Tijd]", Storage="_Datum_en_Tijd", DbType="DateTime")]
		public System.Nullable<System.DateTime> Datum_en_Tijd
		{
			get
			{
				return this._Datum_en_Tijd;
			}
			set
			{
				if ((this._Datum_en_Tijd != value))
				{
					this.OnDatum_en_TijdChanging(value);
					this.SendPropertyChanging();
					this._Datum_en_Tijd = value;
					this.SendPropertyChanged("Datum_en_Tijd");
					this.OnDatum_en_TijdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Productnaam", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Productnaam
		{
			get
			{
				return this._Productnaam;
			}
			set
			{
				if ((this._Productnaam != value))
				{
					this.OnProductnaamChanging(value);
					this.SendPropertyChanging();
					this._Productnaam = value;
					this.SendPropertyChanged("Productnaam");
					this.OnProductnaamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CO-2 uitstoot]", Storage="_CO_2_uitstoot", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string CO_2_uitstoot
		{
			get
			{
				return this._CO_2_uitstoot;
			}
			set
			{
				if ((this._CO_2_uitstoot != value))
				{
					this.OnCO_2_uitstootChanging(value);
					this.SendPropertyChanging();
					this._CO_2_uitstoot = value;
					this.SendPropertyChanged("CO_2_uitstoot");
					this.OnCO_2_uitstootChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
